### PR TITLE
Add support to directly provide `crypto:PrivateKey` and `crypto:PublicKey` in JWT signature configurations

### PR DESCRIPTION
**Pull request by ayeshLK**
Fixes: [#6514](https://github.com/ballerina-platform/ballerina-library/issues/6514)

### Issuing self-signed JWT using `crypto:PrivateKey`
```ballerina
byte[] privateKeyContent = check io:fileReadBytes("path-to/private.key");
crypto:PrivateKey privateKey = check crypto:decodeRsaPrivateKeyFromContent(privateKeyContent);
jwt:IssuerConfig issuerConfig = {
    username: "John",
    issuer: "wso2",
    audience: ["ballerina", "ballerinaSamples"],
    expTime: 600,
    signatureConfig: {
        config: privateKey
    }
};
string jwt = check jwt:issue(issuerConfig);
```

### Validating self-signed JWT using `crypto:PublicKey`
```ballerina
byte[] pubicCertContent = check io:fileReadBytes("path-to/public.crt");
crypto:PublicKey publicKey = check crypto:decodeRsaPublicKeyFromContent(pubicCertContent);
jwt:ValidatorConfig validatorConfig = {
    issuer: "wso2",
    audience: ["ballerina", "ballerinaSamples"],
    clockSkew: 60,
    signatureConfig: {
        certFile: publicKey
    }
};
string jwtContent = "xxxxxx";
jwt:Payload result = check jwt:validate(jwtContent, validatorConfig);
```

## Checklist
- [X] Linked to an issue
- [X] Updated the changelog
- [x] Added tests
- [X] Updated the spec
- [x] Checked native-image compatibility

### CODE REVIEW

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

**Comment by ayeshLK** [comment]
Closing this PR temporarily as we are planning to release this on Update 10.

**Comment by ayeshLK** [comment]
Reopening the PR to release with Update 10.

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

**Pull request merged**
