### PR TITLE
Implement load tests for JWT module

### PR DESCRIPTION
**Pull request by ldclakmal**
## Purpose
This PR implements the load-tests for JWT module with the use of `examples/order-management-service`.

Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2189

---

Tested locally with a Kubernetes cluster as follows:

**Cluster details:**
```shell
➜  ~ kubectl get all
NAME                                              READY   STATUS    RESTARTS   AGE
pod/order-managemen-deployment-76bdd848cb-5sdcl   1/1     Running   0          10s

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
service/kubernetes                  ClusterIP   10.96.0.1        <none>        443/TCP                         5d13h
service/order-managemen             ClusterIP   10.102.76.132    <none>        9445/TCP,9090/TCP               10s
service/order-managemen-svc-local   NodePort    10.108.180.195   <none>        9445:32717/TCP,9090:32366/TCP   4s

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/order-managemen-deployment   1/1     1            1           10s

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/order-managemen-deployment-76bdd848cb   1         1         1       10s

NAME                                                  REFERENCE                               TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/order-managemen   Deployment/order-managemen-deployment   <unknown>/50%   1         1         0          10s
```

**Test details:**
```shell
➜  ~ jmeter -n -t http-post-request.jmx -l original.jtl -Jusers=10 -Jduration=300 -Jhost=localhost -Jport=32366 -Jprotocol=https -Jpath=order -Jresponse_size=50 -Jpayload="./50B.json"
Creating summariser <summary>
Created the tree successfully using http-post-request.jmx
Starting standalone test @ Thu Nov 18 21:58:46 IST 2021 (1637252926203)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
Warning: Nashorn engine is planned to be removed from a future JDK release
summary +      1 in 00:00:19 =    0.1/s Avg: 14746 Min: 14746 Max: 14746 Err:     0 (0.00%) Active: 19 Started: 19 Finished: 0
summary +   1180 in 00:00:24 =   48.2/s Avg:   775 Min:    91 Max: 18595 Err:     0 (0.00%) Active: 44 Started: 44 Finished: 0
summary =   1181 in 00:00:43 =   27.3/s Avg:   786 Min:    91 Max: 18595 Err:     0 (0.00%)
summary +   2375 in 00:00:30 =   78.9/s Avg:   699 Min:   194 Max:  4946 Err:     0 (0.00%) Active: 60 Started: 60 Finished: 0
summary =   3556 in 00:01:13 =   48.5/s Avg:   728 Min:    91 Max: 18595 Err:     0 (0.00%)
summary +   3756 in 00:00:30 =  125.6/s Avg:   468 Min:    18 Max:  2810 Err:     0 (0.00%) Active: 60 Started: 60 Finished: 0
summary =   7312 in 00:01:43 =   70.8/s Avg:   594 Min:    18 Max: 18595 Err:     0 (0.00%)
summary +   5977 in 00:00:30 =  199.4/s Avg:   309 Min:     6 Max:  2184 Err:     0 (0.00%) Active: 60 Started: 60 Finished: 0
summary =  13289 in 00:02:13 =   99.7/s Avg:   466 Min:     6 Max: 18595 Err:     0 (0.00%)
summary +   7150 in 00:00:30 =  238.3/s Avg:   250 Min:     6 Max:  1576 Err:     0 (0.00%) Active: 60 Started: 60 Finished: 0
summary =  20439 in 00:02:43 =  125.2/s Avg:   390 Min:     6 Max: 18595 Err:     0 (0.00%)
summary +   7763 in 00:00:30 =  257.9/s Avg:   231 Min:     3 Max:  1320 Err:     0 (0.00%) Active: 60 Started: 60 Finished: 0
summary =  28202 in 00:03:13 =  145.8/s Avg:   346 Min:     3 Max: 18595 Err:     0 (0.00%)
summary +   7763 in 00:00:30 =  259.7/s Avg:   231 Min:     4 Max:  2292 Err:     0 (0.00%) Active: 60 Started: 60 Finished: 0
summary =  35965 in 00:03:43 =  161.1/s Avg:   321 Min:     3 Max: 18595 Err:     0 (0.00%)
summary +   2776 in 00:01:20 =   34.9/s Avg:  1716 Min:     5 Max: 30039 Err:   180 (6.48%) Active: 0 Started: 60 Finished: 60
summary =  38741 in 00:05:03 =  127.9/s Avg:   421 Min:     3 Max: 30039 Err:   180 (0.46%)
Tidying up ...    @ Thu Nov 18 22:03:49 IST 2021 (1637253229572)
... end of run
```

## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests

### CODE REVIEW

**Review by dilanSachi — DISMISSED** [review]

**Comment by dilanSachi** [comment]
BTW, we need to add the `Automated Summary PR` workflow here. The current workflow in gRPC needs to be changed to send only 1 PR for all the load test summary file commits.

**Comment by ldclakmal** [comment]
> BTW, we need to add the `Automated Summary PR` workflow here. The current workflow in gRPC needs to be changed to send only 1 PR for all the load test summary file commits.

Ack. Will update the PR with that workflow as well.

Found out another issue, let's merge this once it is fixed.

**Comment by dilanSachi** [comment]
> BTW, we need to add the `Automated Summary PR` workflow here. The current workflow in gRPC needs to be changed to send only 1 PR for all the load test summary file commits.

This is fixed in grpc now
https://github.com/ballerina-platform/module-ballerina-grpc/blob/master/.github/workflows/create-summary-pr.yml

**Review by dilanSachi — APPROVED** [review]
LGTM

**Pull request merged**
